field: 5be0de23-5941-4eb3-a5d6-df6dc7a3cf6b
fieldLayouts:
  09034506-bd6e-41e4-87e4-d8ace95fd70b:
    tabs:
      -
        elements:
          -
            fieldUid: 78d7f20a-62f1-4b75-aa52-9aef9ee3ae75
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57d0c07b-d534-4c5f-a128-7de7c995927f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e799ed3-7de9-45b5-9977-7091a293430e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  57d0c07b-d534-4c5f-a128-7de7c995927f:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: "In het bijschrift kun je eventueel vermelden van wie en uit wel jaar het citaat afkomstig is? \r\nBijvoorbeeld: Johan Cruijff (2001)"
    name: Bijschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6e799ed3-7de9-45b5-9977-7091a293430e:
    contentColumnType: text
    fieldGroup: null
    handle: sourceReference
    instructions: 'Vermeld de bron, waar je het citaat vandaan hebt.'
    name: Bronvermelding
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  78d7f20a-62f1-4b75-aa52-9aef9ee3ae75:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: "Als je woorden weglaat uit het citaat moet je het weggelaten deel vervangen door ( ... ) 3 punten, het beletselteken. \r\nHet citaat wordt automatisch voorzien van leestekens aan het begin en einde van het citaat."
    name: Citaat
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockQuote
name: Citaat
sortOrder: 1
