field: ad7cf24d-14fb-4357-a145-3a3e1d9d8224
fieldLayouts:
  f30f607b-53b0-41d2-ba25-febfb0c0f97c:
    tabs:
      -
        elements:
          -
            fieldUid: b9eba0a3-3bbc-4695-a1dc-2b61ede1e513
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7c9c123-33ee-4ce9-abf6-13634f200c3c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b9eba0a3-3bbc-4695-a1dc-2b61ede1e513:
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: ''
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '6'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f7c9c123-33ee-4ce9-abf6-13634f200c3c:
    contentColumnType: string
    fieldGroup: null
    handle: codeType
    instructions: ''
    name: 'Code type'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Twig
            -
              - value
              - twig
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - ExpressionEngine
            -
              - value
              - expressionengine
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Javascript
            -
              - value
              - javascript
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Typescript
            -
              - value
              - typescript
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - VUE
            -
              - value
              - vue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - HTML
            -
              - value
              - html
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - CSS
            -
              - value
              - css
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: code
name: Code
sortOrder: 1
