childBlocks: ''
field: 8b2979ba-f30e-4ef6-b839-f51667e8e3b4
fieldLayouts:
  cb51a5b2-daa4-4d5c-867c-6658afbf2d20:
    tabs:
      -
        elements:
          -
            fieldUid: b3b01e9b-2cdf-4a4c-9b97-4448cc87a504
            instructions: 'Waar moet de link naar toe? En wat is de titel van de link?'
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93e70e01-0109-4af8-b6e6-bf142fe18c2c
            instructions: 'Bepaal de vormgeving van de link hierboven'
            label: Vormgeving
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: button
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Knop
sortOrder: 4
topLevel: true
