childBlocks: ''
field: 8b2979ba-f30e-4ef6-b839-f51667e8e3b4
fieldLayouts:
  14f7268b-f40f-4936-a67f-2dd639f7c4f0:
    tabs:
      -
        elements:
          -
            fieldUid: 27b1d559-bc8d-4309-af2a-b0ec99fd706d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d764be8a-b494-48eb-8a65-6fbab67cf1eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: componentArticleRedactor
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Tekstvak
sortOrder: 1
topLevel: true
