childBlocks: ''
field: 8b2979ba-f30e-4ef6-b839-f51667e8e3b4
fieldLayouts:
  4b0f718f-6e92-4bcf-966c-49932eed2fd2:
    tabs:
      -
        elements:
          -
            fieldUid: 7c737863-69d9-4f38-b813-9bb30cc15966
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: componentHeadline
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Headline
sortOrder: 9
topLevel: true
