childBlocks: ''
field: 8b2979ba-f30e-4ef6-b839-f51667e8e3b4
fieldLayouts:
  46af9ef4-88cf-4dbe-b43e-ac4eabf23a4c:
    tabs:
      -
        elements:
          -
            fieldUid: 97051e39-0f0f-4573-9ddb-a821162275ea
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: componentInfoBlock
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Info blok'
sortOrder: 7
topLevel: true
