childBlocks: ''
field: 8b2979ba-f30e-4ef6-b839-f51667e8e3b4
fieldLayouts:
  9e4668d5-0b8a-494a-ab01-7124e72f7a06:
    tabs:
      -
        elements:
          -
            fieldUid: ad7cf24d-14fb-4357-a145-3a3e1d9d8224
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd037090-bf58-40f1-b64c-5a150f0ccfdb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03550944-a288-4951-a5c8-31657de0c3e4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 62caab8d-1fbe-4974-bb45-44191c74a047
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: componentCode
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Code
sortOrder: 6
topLevel: true
