contentColumnType: string
fieldGroup: 233b1120-3f43-4534-bef0-151f62784c3b
handle: alineaTitle
instructions: "De alinea titel(s) op de pagina.\r\nDeze alinea titels kunnen boven iedere alinea voorkomen, er is geen restrictie aan het gebruik."
name: 'Alinea titel'
searchable: false
settings:
  contentTable: '{{%matrixcontent_alineatitle}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
