contentColumnType: string
fieldGroup: 233b1120-3f43-4534-bef0-151f62784c3b
handle: button
instructions: ''
name: Knop
searchable: false
settings:
  contentTable: '{{%matrixcontent_button}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
