contentColumnType: string
fieldGroup: 233b1120-3f43-4534-bef0-151f62784c3b
handle: sectionTitle
instructions: "De sectie titel(s) op de pagina.\r\nDeze sectie titels kunnen boven iedere sectie voorkomen, er is geen restrictie aan het gebruik."
name: 'Sectie titel'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sectiontitle}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
