contentColumnType: text
fieldGroup: 26f47072-d125-4e06-bd8e-4b9ff5614dbd
handle: seoKeywords
instructions: ''
name: 'SEO keywords'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Voeg keywords toe, gescheiden door een komma'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
